### ISSUE TITLE
Add aboutme.md to "Duran" subdirectory

### ISSUE THREAD

**Issue by brandonmburroughs** [justmarkham/DAT4-students#18]
Hey Duran,

You added the "aboutme.md" file to the root directory.  Please create a subdirectory called "Duran" and move the file there.

**Comment by justmarkham** [comment]
Thanks @brandonmburroughs, I merged it and then created a 'deron' subdirectory and moved it there for him, and let him know! (At this stage, I don't want anyone to have to get stuck trying to figure out how to fix things on their own.)
